In [2]:
import torch

In [24]:
X = torch.rand(size=(7, 7))
X, X.shape

(tensor([[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071],
         [0.6297, 0.3653, 0.8513, 0.8549, 0.5509, 0.2868, 0.2063],
         [0.4451, 0.3593, 0.7204, 0.0731, 0.9699, 0.1078, 0.8829],
         [0.4132, 0.7572, 0.6948, 0.5209, 0.5932, 0.8797, 0.6286],
         [0.7653, 0.1132, 0.8559, 0.6721, 0.6267, 0.5691, 0.7437],
         [0.9592, 0.3887, 0.2214, 0.3742, 0.1953, 0.7405, 0.2529],
         [0.2332, 0.9314, 0.9575, 0.5575, 0.4134, 0.4355, 0.7369]]),
 torch.Size([7, 7]))

In [26]:
#tensor_2 = torch.matmul(torch.rand(1, 7), torch.rand(7, 1))
#torch_reshaped = tensor_2.H
#torch_reshaped, torch_reshaped.shape

Y = torch.rand(size=(1, 7))
Z = torch.matmul(X, Y.T)
Z, Z.shape

(tensor([[1.6774],
         [2.1350],
         [1.9370],
         [2.5315],
         [2.4489],
         [1.5434],
         [2.5353]]), torch.Size([7, 1]))

In [27]:
torch.manual_seed(0)
X = torch.rand(7, 7)
Y = torch.rand(1, 7)

Z = torch.matmul(X, Y.T)
Z, Z.shape

(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]), torch.Size([7, 1]))

In [28]:
device = torch.manual_seed(1234)

In [31]:
torch.manual_seed(1234)

device = "cuda" if torch.cuda.is_available() else "cpu"
print(f'Device: {device}')

tens_6 = torch.rand(2, 3).to(device)
tens_61 = torch.rand(2, 3).to(device)

tens_6, tens_61

Device: cuda


(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))

In [32]:
mul_tensors = torch.matmul(tens_6, tens_61.T)
mul_tensors, mul_tensors.shape


(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]], device='cuda:0'), torch.Size([2, 2]))

In [33]:
max = mul_tensors.max()
min = mul_tensors.min()
max, min

(tensor(0.5617, device='cuda:0'), tensor(0.3647, device='cuda:0'))

In [35]:
arg_max = torch.argmax(mul_tensors)
arg_min = torch.argmin(mul_tensors)
arg_max, arg_min

(tensor(3, device='cuda:0'), tensor(0, device='cuda:0'))

In [36]:
torch.manual_seed(7)

tensor_10 = torch.rand(1, 1, 1, 10)

tensor_10a = tensor_10.squeeze()

print(tensor_10, tensor_10.shape)
print(tensor_10a, tensor_10a.shape)

tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
